### ISSUE TITLE
Permission to CoThings-App/cothings.git denied

### ISSUE THREAD

**Issue by kamilpikula** [rainlab-inc/cothings#26]
hi,
I'd like to make my changes in the code, but I can't publish my branch with changes. Can you check it?
![image](https://user-images.githubusercontent.com/23015380/88163733-68a04400-cc13-11ea-9c3b-a1b0339b1a0f.png)

**Comment by nesimtunc** [comment]
Hi,

You can't directly push to the code base unless you're a member of the organisation with `write` access. Please send a pull request. First, you should fork the project, make your changes in a branch and then send a PR.

Thanks.

**Comment by kamilpikula** [comment]
Okay, thanks for answer. I sent the pull request with basic changes.
